@startuml

!include TwelveDataCryptoPair.puml

TwelveDataREST : cryptoPairs(page: Page) async throws(TwelveDataRESTError) -> TwelveDataCryptoPairsResponse
TwelveDataREST : cryptoPairs() async throws(TwelveDataRESTError) -> TwelveDataCryptoPairsResponse

TwelveDataREST *-- TwelveDataCryptoPairsResponse

@enduml