@startuml

!include Error/TwelveDataRESTError.puml
!include Page/TwelveDataPageConfiguration.puml

struct TwelveDataRESTConfiguration {
    + apiKey: String
    + baseURL: URL
}

struct TwelveDataREST {
    + sessionConfiguration: URLSessionConfiguration
    + configuration: TwelveDataRESTConfiguration
}

TwelveDataREST *-- TwelveDataRESTConfiguration
TwelveDataREST *-- TwelveDataRESTError
TwelveDataREST *-- Page

!include Commodity/TwelveDataREST+Commodity.puml
!include Crypto/TwelveDataREST+Crypto.puml
!include Stocks/TwelveDataREST+Stocks.puml
!include Forex/TwelveDataREST+Forex.puml

title TwelveDataREST

@enduml

/*





*/
